### PR TITLE
soc: update sm4450 to follow actual upstream status

### PR DESCRIPTION
**Pull request by lumag**
Fix few missing entries (like gcc or spinlocks)
Move N/A from comments to the main entry
Mark unsupported-but-present-in-hardware features with explicit N

Cc: YijieYang <quic_yijiyang@quicinc.com>

### CODE REVIEW

**Comment by lumag** [comment]
@yijiyang please take a look and comment

**Comment by yijiyang** [comment]
I will have a check with the upstream kernel again in 2 workdays and comment here.

**Comment by yijiyang** [comment]
If unsupported-but-present-in-hardware features marked as 'N', then what's the meaning of the status left blank?

@lumag

**Comment by lumag** [comment]
@yijiyang blank is 'not known'. Because not everybody has full datasheets, sometimes we is not known whether the feature is supported in hardware (which would mean 'N') or it is not ('N/A').

**Comment by yijiyang** [comment]
After checking and confirmation, I find some divergence:

status-audio-soundwire: N
status-camera-eva: N/A
status-camera-sfe: N/A
status-camera-vfelight: N/A
status-pcie: N
status-storage-ufsice: N

Items not sure now:

status-camera-datapath:
status-msgbox:

@lumag Please check.

**Comment by yijiyang** [comment]
@lumag ping

**Comment by lumag** [comment]
@yijiyang excuse me.

As these features not supported by upstream kernel on this platform it should be either `N` or `N/A` depending whether the hardware supports it or not

> status-audio-soundwire: N

Is soundwire output supported by the platform?

> status-camera-eva: N/A

Again, is EVA a part of the platform or it is not.

> status-camera-sfe: N/A

I was not sure whether the platform has SFE blocks

> status-camera-vfelight: N/A

Same question, I think it has VFE blocks, I was not sure about VFE light

> status-pcie: N

I don't think there is PCIe host on that platform, is it?

> status-storage-ufsice: N

You had 'N/A' in the comment, I moved that to the entry, as comments are supposed to be used for additional details. 

> status-camera-datapath:

Camera datapath is for the camss support on the platform, getting raw images from the sensor. This is not supported by Linux, so `N`.

> status-msgbox:

This entry is for IPCC or APCS msgbox used by remoteprocs. Not supported by Linux, so `N`

**Comment by yijiyang** [comment]
> @yijiyang excuse me.
> 
> As these features not supported by upstream kernel on this platform it should be either `N` or `N/A` depending whether the hardware supports it or not
> 
> > status-audio-soundwire: N
> 
> Is soundwire output supported by the platform?

Hardware supported, confirmed.
> 
> > status-camera-eva: N/A
> 
> Again, is EVA a part of the platform or it is not.

Hardware unsupported, confirmed.
> 
> > status-camera-sfe: N/A
> 
> I was not sure whether the platform has SFE blocks

Hardware unsupported, confirmed.
> 
> > status-camera-vfelight: N/A
> 
> Same question, I think it has VFE blocks, I was not sure about VFE light

Hardware unsupported, confirmed.
> 
> > status-pcie: N
> 
> I don't think there is PCIe host on that platform, is it?

I will have a check again.
> 
> > status-storage-ufsice: N
> 
> You had 'N/A' in the comment, I moved that to the entry, as comments are supposed to be used for additional details.
> 
> > status-camera-datapath:
> 
> Camera datapath is for the camss support on the platform, getting raw images from the sensor. This is not supported by Linux, so `N`.

I'm not sure if it is supported by hardware, so I left it blank.
> 
> > status-msgbox:
> 
> This entry is for IPCC or APCS msgbox used by remoteprocs. Not supported by Linux, so `N`

I'm not sure if it is supported by hardware, so I left it blank.

**Comment by yijiyang** [comment]
PCIe host doesn't exist on this platform, confirmed.
@lumag

**Comment by lumag** [comment]
@yijiyang thanks! Updated and pushed

**Pull request merged**
